// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/global.css";  // Importando o CSS corretamente
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MyTruck",
  description: "Generated by TSF",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div style={{display:"flex"}}>
      <Sidebar />
        <main style={{flex:1,padding: "20px"}}>
          {children}
        </main>
        </div>
        <Footer />
        {children}  {/* O conteúdo da página será injetado aqui */}
      </body>
    </html>
  );
}
